image: openjdk:8-jdk

stages:
  - test

before_script:
  - apt-get update -y
  - apt-get install apt-transport-https -y
  # Install SBT
  - echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
  - apt-get update -y
  - apt-get install sbt -y
  - sbt sbtVersion

test:
  stage: test
  script:
    - sbt clean compile coverage test coverageReport
  cache:
    key: "$CI_COMMIT_SHA"
    paths:
      - target/
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_TAG}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}_scoverage_report"
    paths:
      - "$CI_PROJECT_DIR/target/scala-2.12/scoverage-report"
    expire_in: 1 week