name: BuildAndTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildAndTest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests
      run:
        sbt clean coverage compile test coverageReport
    - name: Upload coverage
      uses: actions/upload-artifact@v2
      with:
        name: scoverage_report
        path: target/scala-2.12/scoverage-report
        retention-days: 7 
